name:                eclipse-bg
version:             0.1.0.0
github:              "traunio/eclipse-bg"
license:             BSD3
author:              "Tapani Raunio"
maintainer:          "tapani.raunio@gmail.com"
copyright:           "Tapani Raunio"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            experimental

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/traunio/eclipse-bg#readme>

dependencies:
- aeson >= 1.1.0.0 
- base >= 4.7 && < 5
- containers >= 0.5
- statistics > 0.14.0.0
- scotty > 0.10.0
- blaze-html > 0.9.0.0
- blaze-markup > 0.8.0.0
- text > 1.0.0.0
- wai-middleware-static > 0.8.0


library:
  source-dirs: src

executables:
  eclipse-bg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eclipse-bg

tests:
  eclipse-bg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eclipse-bg
